/** Стили страниц детального просмотра (офферинг, урок и т.д.) */
import './entity-detail.css';

/** Переиспользуемые UI-компоненты: кнопки, инпуты, модалки, базовая таблица — добавлять по мере необходимости */
export { Alert } from './Alert';
export { FormGroup } from './FormGroup';
export { FormActions } from './FormActions';
export { FormPageLayout } from './FormPageLayout';
export { ConfirmModal } from './ConfirmModal';
export { Modal } from './Modal';
export { PageMessage } from './PageMessage';
export { Drawer } from './Drawer';
export { ScheduleGrid } from './schedule-grid';
export type { ScheduleGridProps, ScheduleEvent } from './schedule-grid';
export { ScheduleToolbar } from './schedule-toolbar';
export type { ScheduleToolbarProps } from './schedule-toolbar';
export { LessonModal } from './lesson-modal';
export type { LessonModalProps } from './lesson-modal';
export { TeacherLessonModal } from './teacher-lesson-modal';
export type { TeacherLessonModalProps } from './teacher-lesson-modal';
export { StudentLessonModal } from './student-lesson-modal';
export type { StudentLessonModalProps } from './student-lesson-modal';
export { LessonEditModal } from './lesson-edit-modal';
export type { LessonEditModalProps } from './lesson-edit-modal';
export { TimeslotsByDayGrid } from './TimeslotsByDayGrid';
export type { TimeslotsByDayGridProps, TimeslotItem } from './TimeslotsByDayGrid';
export { FileCard } from './file-card';
export type { FileCardProps } from './file-card';
export { FileUploadArea } from './file-upload-area/FileUploadArea';
export type { FileUploadAreaProps, FileUploadItem } from './file-upload-area/FileUploadArea';
export { LessonMaterialModal } from './lesson-material-modal';
export type { LessonMaterialModalProps } from './lesson-material-modal';
export { HomeworkModal } from './homework-modal';
export type { HomeworkModalProps } from './homework-modal';
export { StudentGradeHistoryModal } from './student-grade-history-modal';
export type { StudentGradeHistoryModalProps } from './student-grade-history-modal';
export { StudentGradeHistoryDialog } from './student-grade-history-dialog';
export type { StudentGradeHistoryDialogProps } from './student-grade-history-dialog';
export { StudentAttendanceHistoryModal } from './student-attendance-history-modal';
export type { StudentAttendanceHistoryModalProps } from './student-attendance-history-modal';
export { StudentHomeworkHistoryModal } from './student-homework-history-modal';
export type { StudentHomeworkHistoryModalProps } from './student-homework-history-modal';
export { HomeworkHistoryDialog } from './homework-history-dialog';
export type { HomeworkHistoryDialogProps } from './homework-history-dialog';
export { StudentAttendanceHistoryDialog } from './student-attendance-history-dialog';
export type { StudentAttendanceHistoryDialogProps } from './student-attendance-history-dialog';
export { SubjectCard } from './subject-card';
export type { SubjectCardProps } from './subject-card';
export { SemesterFilterSelect } from './semester-filter-select';
export type { SemesterFilterSelectProps } from './semester-filter-select';
export { LessonOverviewCard } from './lesson-overview-card/LessonOverviewCard';
export type { LessonOverviewCardProps } from './lesson-overview-card/LessonOverviewCard';
export { LessonMaterialItemView } from './lesson-material-item-view';
export type { LessonMaterialItemViewProps } from './lesson-material-item-view';
export { HomeworkItemView } from './homework-item-view';
export type { HomeworkItemViewProps } from './homework-item-view';
export { PageHero } from './page-hero';
export type { PageHeroProps } from './page-hero';
export { BackLink } from './back-link';
export type { BackLinkProps } from './back-link';
export { SectionCard } from './section-card';
export type { SectionCardProps } from './section-card';
export { InfoTile } from './info-tile';
export type { InfoTileProps } from './info-tile';
export { DetailMaterialRow } from './detail-material-row';
export type { DetailMaterialRowProps } from './detail-material-row';
export { DetailFileRow } from './detail-file-row';
export type { DetailFileRowProps } from './detail-file-row';
export { StatCard } from './stat-card';
export type { StatCardProps, StatCardAccent } from './stat-card';
export { LessonMaterialDetailView } from './lesson-material-detail-view';
export type { LessonMaterialDetailViewProps } from './lesson-material-detail-view';
export { HomeworkDetailView } from './homework-detail-view';
export type { HomeworkDetailViewProps } from './homework-detail-view';
export { LessonInfoGrid } from './lesson-info-grid';
export type { LessonInfoGridProps } from './lesson-info-grid';
export { AbsenceRequestsFiltersBar } from './absence-requests-filters';
export type { AbsenceRequestsFiltersBarProps } from './absence-requests-filters';
